### ISSUE TITLE
Failed to create template.

### ISSUE THREAD

**Issue by InCogNiTo124** [arthomnix/KerbalDev#1]
This happens in Rider right after starting a new project with SpaceWarp template

The entire stack trace is here:
```
Failed to create template. Details:
Error while processing file /swinfo_id/swinfo.json System.UnauthorizedAccessException: Access to the path 'C:\swinfo.json' is denied.
at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
at System.IO.File.Create(String path)
at Microsoft.TemplateEngine.Utils.PhysicalFileSystem.CreateFile(String path)
at Microsoft.TemplateEngine.Core.Util.Orchestrator.ProcessFile(IFile sourceFile, String sourceRel, String targetDir, IGlobalRunSpec spec, IProcessor fallback, IEnumerable`1 fileGlobProcessors)
```

The solutions seems OK tho (it opens with Rider)

**Comment by arthomnix** [comment]
I think this may be caused by not filling in all the parameters - everything apart from description and source URL are required (there's no validation as Rider can't validate .net template parameters as far as I know, but the solution will be broken if you don't fill them in)

**Comment by InCogNiTo124** [comment]
That is quite correct. I tried filling dummy values and it works now. Thank you for the prompt response!

> (there's no validation as Rider can't validate .net template parameters as far as I know

So this means there is no fix? Too bad ://

**Comment by arthomnix** [comment]
A fix isn't possible as far as I know, but it is documented in the readme that the parameters must be filled in.
